[package]
name = "dmodel"
description = "Model Library"
version = "0.1.0"
edition = "2021"
license= "MIT"

[dependencies]
uuid = { version = "0.8", features = ["serde", "v4"] }
thiserror="1.0.30"
log="0.4.14"
